### ISSUE TITLE
Cannot read property 'canAddPasses' of undefined

### ISSUE THREAD

**Issue by RP20** [erikpoort/react-native-wallet#2]
Looks like it's not calling any native iOS methods. I tried deleting node_modules and installing packages again to work react-native-link. Still no luck with that.
<img width="548" alt="screen shot 2017-12-06 at 8 29 15 pm" src="https://user-images.githubusercontent.com/19157036/33698864-2bef16a0-dac4-11e7-859c-908b71215cd8.png">

Is there anything that I might be missing?

<img width="376" alt="screen shot 2017-12-05 at 11 03 49 am" src="https://user-images.githubusercontent.com/19157036/33698819-d3383e9c-dac3-11e7-9235-174ef26a40ea.png">

FYI 
**I am calling below function on button click.**
```
Wallet.canAddPasses()
      .then(res => {
          console.log(res);
      })
      .catch((e) => {
          console.log(e);
      });
```

**Comment by ErikMediaMonks** [comment]
Hi RP20, 
Sorry for the delayed response!
The 'canAddPasses' is a really straightforward call in native iOS. It's synchronous and returns a boolean. So it didn't make sense to me to return a promise here.
Please try:
`Wallet.canAddPasses(added => {
	// Handle rest
});`
Hope this helps!
