### ISSUE TITLE
There's a typo causing showAddPassControllerFromURL to crash

### ISSUE THREAD

**Issue by getreup** [erikpoort/react-native-wallet#6]
In index.js, line 20, _showAddPassControllerFromString should be _showAddPassControllerFromURL.

**Comment by erikpoort** [comment]
I'm on holidays right now so I can't change it, but feel free to do a PR!
Or ask @ jgfidelis who missed this call on a rename :)

**Comment by sibelius** [comment]
@jgfidelis
